# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clayton_rot_logdens_cpp <- function(U, theta) {
    .Call(`_TDMRC_clayton_rot_logdens_cpp`, U, theta)
}

sample_z_cpp <- function(U, theta, pi) {
    .Call(`_TDMRC_sample_z_cpp`, U, theta, pi)
}

theta_component_loglik_cpp <- function(U, theta, Z) {
    .Call(`_TDMRC_theta_component_loglik_cpp`, U, theta, Z)
}

z_col_sums_cpp <- function(Z) {
    .Call(`_TDMRC_z_col_sums_cpp`, Z)
}

