// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// clayton_rot_logdens_cpp
NumericMatrix clayton_rot_logdens_cpp(const NumericMatrix& U, const NumericVector& theta);
RcppExport SEXP _TDMRC_clayton_rot_logdens_cpp(SEXP USEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type U(USEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(clayton_rot_logdens_cpp(U, theta));
    return rcpp_result_gen;
END_RCPP
}
// sample_z_cpp
IntegerMatrix sample_z_cpp(const NumericMatrix& U, const NumericVector& theta, const NumericVector& pi);
RcppExport SEXP _TDMRC_sample_z_cpp(SEXP USEXP, SEXP thetaSEXP, SEXP piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type U(USEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pi(piSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_z_cpp(U, theta, pi));
    return rcpp_result_gen;
END_RCPP
}
// theta_component_loglik_cpp
NumericVector theta_component_loglik_cpp(const NumericMatrix& U, const NumericVector& theta, const IntegerMatrix& Z);
RcppExport SEXP _TDMRC_theta_component_loglik_cpp(SEXP USEXP, SEXP thetaSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type U(USEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(theta_component_loglik_cpp(U, theta, Z));
    return rcpp_result_gen;
END_RCPP
}
// z_col_sums_cpp
NumericVector z_col_sums_cpp(const IntegerMatrix& Z);
RcppExport SEXP _TDMRC_z_col_sums_cpp(SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(z_col_sums_cpp(Z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TDMRC_clayton_rot_logdens_cpp", (DL_FUNC) &_TDMRC_clayton_rot_logdens_cpp, 2},
    {"_TDMRC_sample_z_cpp", (DL_FUNC) &_TDMRC_sample_z_cpp, 3},
    {"_TDMRC_theta_component_loglik_cpp", (DL_FUNC) &_TDMRC_theta_component_loglik_cpp, 3},
    {"_TDMRC_z_col_sums_cpp", (DL_FUNC) &_TDMRC_z_col_sums_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_TDMRC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
